// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtrxyuKq4rTC-UeHqThq4vQqHlVDFwIw',
    appId: '1:817432477193:web:ad3c7dce7d6581883242d8',
    messagingSenderId: '817432477193',
    projectId: 'mylez-flutter-flash-chat',
    authDomain: 'mylez-flutter-flash-chat.firebaseapp.com',
    storageBucket: 'mylez-flutter-flash-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqZQri4wvCXnMJkSrWEfidaOr-u16raA',
    appId: '1:817432477193:android:d231bd1b9d2f001e3242d8',
    messagingSenderId: '817432477193',
    projectId: 'mylez-flutter-flash-chat',
    storageBucket: 'mylez-flutter-flash-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCqRmmaxO332KpT3GUc_AEXh8e2rECQs',
    appId: '1:817432477193:ios:a0d7602f12422b5a3242d8',
    messagingSenderId: '817432477193',
    projectId: 'mylez-flutter-flash-chat',
    storageBucket: 'mylez-flutter-flash-chat.appspot.com',
    iosClientId: '817432477193-3u0jq66jo2ct9ffn74bice7hoocjndq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
